default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  database: db/development.sqlite3

test:
  database: db/test.sqlite3

production:
  adapter: pg
  database: db/production.pg
