# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d4aab96631574a7c81614ee8dfa4002b0eab13553fa7a4e9dcf7038b881888d4bf5df21357051a915cf51aef86ef6cacfc2d4741e57f0833462dc093b250df0

test:
  secret_key_base: d1fc385573ef9a68e7c012653b40f78c91ea08313f4b5e9377c84e34e0dff0532897809be249d42939e31295b5f52e37769f7f0248275c8f27c3c524be56a3c8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
